// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/license/mit/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cartas/": {
            "get": {
                "description": "este método devuelve una lista de documentos tipo Carta",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cartas"
                ],
                "summary": "trae una lista de documentos tipo Carta",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tamaño de la paginación",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Página de los documentos",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Coleccion del documento",
                        "name": "coleccion",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Si se activa el filtro, solo trae las cartas activas",
                        "name": "statusFilter",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de documentos tipo Carta",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "Parámetros de paginación inválidos",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error interno en el servidor",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cartas/name/": {
            "get": {
                "description": "este método devuelve una lista de documentos tipo Carta filtrado por nombre",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cartas"
                ],
                "summary": "trae una lista de documentos tipo Carta filtrado por nombre",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tamaño de la paginación",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Página de los documentos",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "palabra clave para filtrar",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Coleccion del documento",
                        "name": "coleccion",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de documentos tipo Carta",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "400": {
                        "description": "Parámetros de paginación inválidos",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error interno en el servidor",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cartas/{id}": {
            "get": {
                "description": "este método devuelve un documento tipo Carta por búsqueda de id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cartas"
                ],
                "summary": "trae un documento tipo Carta",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la Carta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Documento tipo Carta",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Id de búsqueda inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Documento no existente en la base de datos",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/consumible/": {
            "get": {
                "description": "este método devuelve una lista de documentos tipo Consumible",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consumible"
                ],
                "summary": "trae una lista de documentos tipo Consumible",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tamaño de la paginación",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Página de los documentos",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Coleccion del documento",
                        "name": "coleccion",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Si se activa el filtro, solo trae las cartas activas",
                        "name": "statusFilter",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de documentos tipo Consumible",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ConsumibleModel"
                            }
                        }
                    },
                    "400": {
                        "description": "Parámetros de paginación inválidos",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error interno en el servidor",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/consumible/name/": {
            "get": {
                "description": "este método devuelve una lista de documentos tipo Consumible filtrado por nombre",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consumible"
                ],
                "summary": "trae una lista de documentos tipo Consumible filtrado por nombre",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tamaño de la paginación",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Página de los documentos",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "palabra clave para filtrar",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Coleccion del documento",
                        "name": "coleccion",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de documentos tipo Consumible",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ConsumibleModel"
                            }
                        }
                    },
                    "400": {
                        "description": "Parámetros de paginación inválidos",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error interno en el servidor",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/heroes/": {
            "get": {
                "description": "este método devuelve una lista de documentos tipo Heroe",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Heroes"
                ],
                "summary": "trae una lista de documentos tipo Heroe",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tamaño de la paginación",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Página de los documentos",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Si se activa el filtro, solo trae las cartas activas",
                        "name": "statusFilter",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de documentos tipo Heroe",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.HeroeModel"
                            }
                        }
                    },
                    "400": {
                        "description": "Parámetros de paginación inválidos",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error interno en el servidor",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "este método recibe los parámetros de tipo Heroe y crea la carta",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Heroes"
                ],
                "summary": "crea un documento tipo Heroe",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Imagen de la carta",
                        "name": "imagen",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Icono de la carta",
                        "name": "icono",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nombre de la carta",
                        "name": "nombre",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Clase de la carta",
                        "name": "clase",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tipo de la carta",
                        "name": "tipo",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Poder de la carta",
                        "name": "poder",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Vida de la carta",
                        "name": "vida",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "defensa de la carta",
                        "name": "defensa",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Ataque base de la carta",
                        "name": "ataqueBase",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Ataque aleatorio de la carta",
                        "name": "ataqueRnd",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Daño de la carta",
                        "name": "daño",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Descripción de la carta",
                        "name": "descripcion",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "[Ecommerce] Precio de la carta",
                        "name": "precio",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "[Ecommerce] Descuento de la carta",
                        "name": "descuento",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "[Ecommerce] Stock de la carta",
                        "name": "stock",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Documento creado exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Parámetros de paginación inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno en el servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "este método recibe los parámetros de tipo Heroe y actualiza la carta",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Heroes"
                ],
                "summary": "actualiza un documento tipo Heroe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id de la carta",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Imagen de la carta",
                        "name": "imagen",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Icono de la carta",
                        "name": "icono",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Nombre de la carta",
                        "name": "nombre",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Poder de la carta",
                        "name": "poder",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Vida de la carta",
                        "name": "vida",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "defensa de la carta",
                        "name": "defensa",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Ataque base de la carta",
                        "name": "ataqueBase",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Ataque aleatorio de la carta",
                        "name": "ataqueRnd",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Daño de la carta",
                        "name": "daño",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Descripción de la carta",
                        "name": "descripcion",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "[Ecommerce] Precio de la carta",
                        "name": "precio",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "[Ecommerce] Descuento de la carta",
                        "name": "descuento",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "[Ecommerce] Stock de la carta",
                        "name": "stock",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "Activar o desactivar la carta",
                        "name": "estado",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Documento actualizado exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Parámetros de paginación inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error interno en el servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/heroes/name/": {
            "get": {
                "description": "este método devuelve una lista de documentos tipo Heroe filtrado por nombre",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Heroes"
                ],
                "summary": "trae una lista de documentos tipo Heroe filtrado por nombre",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tamaño de la paginación",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Página de los documentos",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "palabra clave para filtrar",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de documentos tipo Heroe",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.HeroeModel"
                            }
                        }
                    },
                    "400": {
                        "description": "Parámetros de paginación inválidos",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error interno en el servidor",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ConsumibleModel": {
            "type": "object",
            "required": [
                "clase",
                "coleccion",
                "descripcion",
                "descuento",
                "efecto",
                "efectoHeroe",
                "estado",
                "icono",
                "imagen",
                "nombre",
                "precio",
                "stock",
                "tipo"
            ],
            "properties": {
                "clase": {
                    "type": "string",
                    "enum": [
                        "Guerrero",
                        "Mago",
                        "Pícaro"
                    ]
                },
                "coleccion": {
                    "type": "string",
                    "enum": [
                        "Heroes",
                        "Armas",
                        "Armaduras",
                        "Items",
                        "Épicas"
                    ]
                },
                "descripcion": {
                    "type": "string"
                },
                "descuento": {
                    "type": "integer",
                    "minimum": 0
                },
                "efecto": {
                    "type": "object",
                    "additionalProperties": true
                },
                "efectoHeroe": {
                    "type": "object",
                    "additionalProperties": true
                },
                "estado": {
                    "type": "boolean"
                },
                "icono": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imagen": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "precio": {
                    "type": "integer",
                    "minimum": 0
                },
                "stock": {
                    "type": "integer",
                    "minimum": 0
                },
                "tipo": {
                    "type": "string",
                    "enum": [
                        "Tanque",
                        "Armas",
                        "Fuego",
                        "Hielo",
                        "Veneno",
                        "Machete"
                    ]
                }
            }
        },
        "models.HeroeModel": {
            "type": "object",
            "required": [
                "ataqueBase",
                "ataqueRnd",
                "clase",
                "coleccion",
                "daño",
                "defensa",
                "descripcion",
                "descuento",
                "estado",
                "icono",
                "imagen",
                "nombre",
                "poder",
                "precio",
                "stock",
                "tipo",
                "vida"
            ],
            "properties": {
                "ataqueBase": {
                    "type": "integer"
                },
                "ataqueRnd": {
                    "type": "integer"
                },
                "clase": {
                    "type": "string",
                    "enum": [
                        "Guerrero",
                        "Mago",
                        "Pícaro"
                    ]
                },
                "coleccion": {
                    "type": "string",
                    "enum": [
                        "Heroes",
                        "Armas",
                        "Armaduras",
                        "Items",
                        "Épicas"
                    ]
                },
                "daño": {
                    "type": "integer"
                },
                "defensa": {
                    "type": "integer"
                },
                "descripcion": {
                    "type": "string"
                },
                "descuento": {
                    "type": "integer",
                    "minimum": 0
                },
                "estado": {
                    "type": "boolean"
                },
                "icono": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imagen": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "poder": {
                    "type": "integer"
                },
                "precio": {
                    "type": "integer",
                    "minimum": 0
                },
                "stock": {
                    "type": "integer",
                    "minimum": 0
                },
                "tipo": {
                    "type": "string",
                    "enum": [
                        "Tanque",
                        "Armas",
                        "Fuego",
                        "Hielo",
                        "Veneno",
                        "Machete"
                    ]
                },
                "vida": {
                    "type": "integer"
                }
            }
        }
    },
    "externalDocs": {
        "description": "Repository",
        "url": "https://github.com/JDKdevStudio/TheNexusBattlesII_Card_API_Reborn"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "The Nexus Battles II: Card API Service Reborn",
	Description:      "Servicio API para acceder a las cartas del negocio",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
